# Generated by Django 3.0.6 on 2020-05-14 20:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignedDate', models.DateField(auto_now_add=True, verbose_name='Atama Tarihi')),
                ('dueDate', models.DateField(verbose_name='Miat')),
                ('task', models.CharField(max_length=200, verbose_name='Görev')),
                ('details', models.TextField(verbose_name='Açıklamalar')),
                ('assignedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager', to=settings.AUTH_USER_MODEL)),
                ('assignedTo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignee', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
